--PROPOSTA_AUTO
ALTER TABLE PROPOSTA_AUTO
    ADD USUARIO_ANALISE NUMBER(19);

ALTER TABLE PROPOSTA_AUTO
    ADD CONSTRAINT FK_PROPOSTA_AUTO_USR_ANALISE
        FOREIGN KEY (USUARIO_ANALISE)
        REFERENCES USUARIO(CODIGO);