CREATE TABLE USUARIO
(
  codigo NUMBER NOT NULL ,
  nome   VARCHAR2(100) NOT NULL,
  CONSTRAINT USUARIO_PK PRIMARY KEY (codigo)
);

CREATE TABLE LOGIN_USUARIO (
  usuario NUMBER NOT NULL,
  senha   VARCHAR2(100) NOT NULL,
  CONSTRAINT pk_login PRIMARY KEY (usuario),
  CONSTRAINT fk_login_usuario FOREIGN KEY (usuario) REFERENCES USUARIO(codigo)
);

CREATE TABLE STATUS_PROPOSTA
(
  codigo NUMBER NOT NULL ,
  descricao   VARCHAR2(100) NOT NULL,
  CONSTRAINT STATUS_PROPOSTA_PK PRIMARY KEY (codigo)
);

-- ===========================================================
-- TABELA: TELEFONE
-- ===========================================================
CREATE TABLE TELEFONE (
    ID NUMBER(10) PRIMARY KEY,
    DDD VARCHAR2(20 CHAR) NOT NULL,
    NUMERO VARCHAR2(20 CHAR) NOT NULL,
    TIPO VARCHAR2(20 CHAR)
);

CREATE SEQUENCE SEQ_TELEFONE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


-- ===========================================================
-- TABELA: ENDERECO
-- ===========================================================
CREATE TABLE ENDERECO (
    ID NUMBER(10) PRIMARY KEY,
    LOGRADOURO VARCHAR2(150 CHAR) NOT NULL,
    NUMERO VARCHAR2(10 CHAR),
    COMPLEMENTO VARCHAR2(100 CHAR),
    BAIRRO VARCHAR2(100 CHAR),
    CIDADE VARCHAR2(100 CHAR),
    ESTADO VARCHAR2(2 CHAR),
    CEP VARCHAR2(8 CHAR)
);

CREATE SEQUENCE SEQ_ENDERECO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


-- ===========================================================
-- TABELA: CLIENTE
-- ===========================================================
CREATE TABLE CLIENTE (
    ID NUMBER(10) PRIMARY KEY,
    NOME VARCHAR2(100 CHAR) NOT NULL,
    NOME_MAE VARCHAR2(100 CHAR) NOT NULL,
    NOME_PAI VARCHAR2(100 CHAR),
    EMAIL VARCHAR2(100 CHAR) UNIQUE NOT NULL,
    RG VARCHAR2(9 CHAR) UNIQUE NOT NULL,
    CPF VARCHAR2(11 CHAR) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE,
    TELEFONE_ID NUMBER(10),
    ENDERECO_ID NUMBER(10),
    PROFISSAO_ID NUMBER(10),
    CONSTRAINT FK_CLIENTE_TELEFONE FOREIGN KEY (TELEFONE_ID)
        REFERENCES TELEFONE(ID),
    CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (ENDERECO_ID)
        REFERENCES ENDERECO(ID),
    CONSTRAINT FK_CLIENTE_PROFISSAO FOREIGN KEY (PROFISSAO_ID)
        REFERENCES PROFISSAO(ID)
);

CREATE SEQUENCE SEQ_CLIENTE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ===========================================================
-- TABELA: GARANTIA
-- ===========================================================
CREATE TABLE GARANTIA (
    ID NUMBER(10) PRIMARY KEY,
    MARCA VARCHAR2(50 CHAR) NOT NULL,
    MODELO VARCHAR2(100 CHAR),
    ANO_MODELO   NUMBER(4) NOT NULL,
    ANO_FABRICACAO   NUMBER(4)  NOT NULL,
    VALOR            NUMBER(18,2) NOT NULL
);

CREATE SEQUENCE SEQ_GARANTIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


-- ===========================================================
-- TABELA: PROFISSAO
-- ===========================================================
CREATE TABLE PROFISSAO (
    ID NUMBER(10) PRIMARY KEY,
    PROFISSAO VARCHAR2(50 CHAR) NOT NULL,
    RENDA      NUMBER(18,2) NOT NULL
);

CREATE SEQUENCE SEQ_PROFISSAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE SEQUENCE SEQ_PROPOSTA_AUTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE PROPOSTA_AUTO (
    PROPOSTA           NUMBER(19)      NOT NULL,
    STATUS             NUMBER(19)      NOT NULL,
    PRODUTO            VARCHAR2(255),
    DATA_CADASTRO      TIMESTAMP       NOT NULL,
    DATA_ATUALIZACAO   TIMESTAMP,
    INICIO_ANALISE     TIMESTAMP,
    FIM_ANALISE        TIMESTAMP,
    USUARIO_CADASTRO   NUMBER(19)      NOT NULL,
    USUARIO_ALTERACAO  NUMBER(19),
    VALOR              NUMBER(18,2),
    CLIENTE_ID         NUMBER(10)  NOT NULL,
    GARANTIA_ID         NUMBER(10)  NOT NULL,

    CONSTRAINT PK_PROPOSTA_AUTO PRIMARY KEY (PROPOSTA),
    CONSTRAINT FK_PROPOSTA_AUTO_STATUS FOREIGN KEY (STATUS) REFERENCES STATUS_PROPOSTA(CODIGO),
    CONSTRAINT FK_PROPOSTA_AUTO_USR_CAD FOREIGN KEY (USUARIO_CADASTRO) REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_PROPOSTA_AUTO_USR_ALT FOREIGN KEY (USUARIO_ALTERACAO) REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_PROPOSTA_AUTO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
    CONSTRAINT FK_PROPOSTA_AUTO_GARANTIA FOREIGN KEY (GARANTIA_ID) REFERENCES GARANTIA(ID)
);

